### ISSUE TITLE
setRotation support

### ISSUE THREAD

**Issue by emilyvelasco** [Roger-random/ESP_8_BIT_composite#21]
Would it be possible to support the setRotation function present in the Adafruit GFX library in this library? There might be occasions where someone would need to display an image on a composite video monitor rotated to 90, 180 or 270 degrees.

**Comment by Roger-random** [comment]
Should be possible. Brief code review didn't find any immediate dealbreakers, I will know more once I dig deeper.

When I built this library I had a big awkward CRT TV that I wouldn't want to turn on its side (or upside-down) and I selfishly neglected to consider someone else may have a smaller CRT practical for rotation. Oops.

**Comment by emilyvelasco** [comment]
Not selfish at all! Most people will probably never turn a CRT TV on its side ever in their lives

**Comment by Roger-random** [comment]
It turns out to be pretty straightforward. I've just published `setRotation()` support in v1.3.0.
Version release: #22 
GitHub commit: 8f80471815ffbe2d6cf427962bb8f3591a60d95b
