### ISSUE TITLE
Warning when compiling.

### ISSUE THREAD

**Issue by limaomerces** [Roger-random/ESP_8_BIT_composite#35]
```
ESP_8_BIT_composite-main\ESP_8_BIT_GFX.cpp: In member function 'uint8_t ESP_8_BIT_GFX::getColor8(uint16_t)':
ESP_8_BIT_composite-main\ESP_8_BIT_GFX.cpp:262:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

This message is displayed whenever I launch the IDE to check the code. I imagine it is not desirable. So I'm bringing it for you to review.

Arduino IDE 1.8.19
Esp Board (Arduino IDE): 2.0.3 -RC1

**Comment by Roger-random** [comment]
Thank you for reporting! I will investigate.
