### ISSUE TITLE
Need help interfacing sd card with esp32

### ISSUE THREAD

**Issue by Diexd367** [Roger-random/ESP_8_BIT_composite#48]
Hi roger
I need sd card support for the animatedgif example.And im struggling to do that as my attempts lead to no sucess.
Can you send me the example but instead of using 
.h file it opens a file  /example.gif and also add the ability to cycle through gifs like the animatedgif library examples.
Thanks!!

**Comment by Roger-random** [comment]
I don't have such an example to send you, sorry. All my examples are in the examples folder of this library, none of them interface with a SD card.
