### ISSUE TITLE
How to stop display initiation? 

### ISSUE THREAD

**Issue by ShiveStar** [Roger-random/ESP_8_BIT_composite#51]
I have run into an issue where after init this library using "display.begin();" I am having the issue where the Bluetooth code I am running alongside this no longer functions properly. Is there a way I can undo the display.begin()? My plan is just to declare display.begin(); whenever I need the display and then otherwise have it deinitialized to enable the rest of my code to function properly. Thanks!

**Comment by Roger-random** [comment]
The code you seek is in class destructor (`ESP_8_BIT_composite::~ESP_8_BIT_composite()`) which cleans up everything set up in `begin()`.
